


---
- name: Create Ansible User
  hosts: all
  
  tasks:  
#create ansible user
  - name: Add Ansible user
    user:
      name: ansible
      comment: User with privilages for ansible
      group: wheel
      state: present
      shell: /bin/bash
    become: yes
    become_user: root
    become_method: sudo

#ADD Sudoers
  - name: Add devops user to the sudoers
    copy:
      dest: "/etc/sudoers.d/ansible"
      content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
    become: yes
    become_user: root
    become_method: sudo

#COPY SSH Key
  - name: Deploy SSH Key
    authorized_key:
      user: ansible
      state: present
      key: "{{ lookup('file', '/home/ansible/.ssh/id_ed25519.pub') }}"

