---
# tasks file for rhel


- name: instal updates
  yum:
    name: '*'
    state: latest
  when: ansible_os_family == "Redhat"

- name: Reboot after upgrade
  reboot:

  name: Wait for server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=10
  become: false


